// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(nameFFI)
import nameFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_name_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_name_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureNameInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum Name: Equatable, Hashable {
    
    case god
    case cronos
    case cronus
    case kronos
    case zeus
    case hera
    case leto
    case hermes
    case apollo
    case artemis
    case achilles
    case philip
    case cyrus
    case יֵשׁוּ
    case יֵשׁוּעַ
    case ἰησοῦς
    case iesus
    case genesis
    case exodus
    case leviticus
    case numbers
    case deuteronomy
    case joshua
    case judges
    case ruth
    case samuelI
    case samuelIi
    case kingsI
    case kingsIi
    case chroniclesI
    case chroniclesIi
    case ezra
    case nehemiah
    case esther
    case job
    case psalms
    case proverbs
    case ecclesiastes
    case songOfSolomon
    case isaiah
    case jeremiah
    case lamentations
    case ezekiel
    case daniel
    case hosea
    case joel
    case amos
    case obadiah
    case jonah
    case micah
    case nahum
    case habakkuk
    case zephaniah
    case haggai
    case zechariah
    case malachi
    case matthew
    case mark
    case luke
    case john
    case acts
    case romans
    case corinthiansI
    case corinthiansIi
    case galatians
    case ephesians
    case philippians
    case colossians
    case thessaloniansI
    case thessaloniansIi
    case timothyI
    case timothyIi
    case titus
    case philemon
    case hebrews
    case james
    case peterI
    case peterIi
    case johnI
    case johnIi
    case johnIii
    case jude
    case revelation
    case yahweh
    case mary
    case adam
    case eve
    case cain
    case abel
    case seth
    case enosh
    case kenan
    case mahalalel
    case jared
    case enoch
    case methuselah
    case lamech
    case noah
    case shem
    case arphaxad
    case cainan
    case shelah
    case eber
    case peleg
    case reu
    case serug
    case nahor
    case terrah
    case abraham
    case isaac
    case jacob
    case israel
    case reuben
    case amram
    case jochebed
    case moses
    case aaron
    case perez
    case hezron
    case ram
    case amminadab
    case nashon
    case salmon
    case boaz
    case obed
    case jesse
    case david
    case nathan
    case mattatha
    case menna
    case melea
    case eliakim
    case jonam
    case judah
    case simeon
    case jorim
    case eliezer
    case er
    case elmadam
    case cosam
    case addi
    case neri
    case shealtiel
    case zerubbabel
    case rhesa
    case joanan
    case joda
    case josek
    case semein
    case maath
    case naggai
    case esli
    case mattathias
    case jannai
    case melki
    case levi
    case matthat
    case heli
    case joseph
    case mercury
    case diana
    case romulus
    case remus
    case socrates
    case plato
    case aristotle
    case alexander
    case caesar
    case cicero
    case jesus





}

#if compiler(>=6)
extension Name: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeName: FfiConverterRustBuffer {
    typealias SwiftType = Name

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Name {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .god
        
        case 2: return .cronos
        
        case 3: return .cronus
        
        case 4: return .kronos
        
        case 5: return .zeus
        
        case 6: return .hera
        
        case 7: return .leto
        
        case 8: return .hermes
        
        case 9: return .apollo
        
        case 10: return .artemis
        
        case 11: return .achilles
        
        case 12: return .philip
        
        case 13: return .cyrus
        
        case 14: return .יֵשׁוּ
        
        case 15: return .יֵשׁוּעַ
        
        case 16: return .ἰησοῦς
        
        case 17: return .iesus
        
        case 18: return .genesis
        
        case 19: return .exodus
        
        case 20: return .leviticus
        
        case 21: return .numbers
        
        case 22: return .deuteronomy
        
        case 23: return .joshua
        
        case 24: return .judges
        
        case 25: return .ruth
        
        case 26: return .samuelI
        
        case 27: return .samuelIi
        
        case 28: return .kingsI
        
        case 29: return .kingsIi
        
        case 30: return .chroniclesI
        
        case 31: return .chroniclesIi
        
        case 32: return .ezra
        
        case 33: return .nehemiah
        
        case 34: return .esther
        
        case 35: return .job
        
        case 36: return .psalms
        
        case 37: return .proverbs
        
        case 38: return .ecclesiastes
        
        case 39: return .songOfSolomon
        
        case 40: return .isaiah
        
        case 41: return .jeremiah
        
        case 42: return .lamentations
        
        case 43: return .ezekiel
        
        case 44: return .daniel
        
        case 45: return .hosea
        
        case 46: return .joel
        
        case 47: return .amos
        
        case 48: return .obadiah
        
        case 49: return .jonah
        
        case 50: return .micah
        
        case 51: return .nahum
        
        case 52: return .habakkuk
        
        case 53: return .zephaniah
        
        case 54: return .haggai
        
        case 55: return .zechariah
        
        case 56: return .malachi
        
        case 57: return .matthew
        
        case 58: return .mark
        
        case 59: return .luke
        
        case 60: return .john
        
        case 61: return .acts
        
        case 62: return .romans
        
        case 63: return .corinthiansI
        
        case 64: return .corinthiansIi
        
        case 65: return .galatians
        
        case 66: return .ephesians
        
        case 67: return .philippians
        
        case 68: return .colossians
        
        case 69: return .thessaloniansI
        
        case 70: return .thessaloniansIi
        
        case 71: return .timothyI
        
        case 72: return .timothyIi
        
        case 73: return .titus
        
        case 74: return .philemon
        
        case 75: return .hebrews
        
        case 76: return .james
        
        case 77: return .peterI
        
        case 78: return .peterIi
        
        case 79: return .johnI
        
        case 80: return .johnIi
        
        case 81: return .johnIii
        
        case 82: return .jude
        
        case 83: return .revelation
        
        case 84: return .yahweh
        
        case 85: return .mary
        
        case 86: return .adam
        
        case 87: return .eve
        
        case 88: return .cain
        
        case 89: return .abel
        
        case 90: return .seth
        
        case 91: return .enosh
        
        case 92: return .kenan
        
        case 93: return .mahalalel
        
        case 94: return .jared
        
        case 95: return .enoch
        
        case 96: return .methuselah
        
        case 97: return .lamech
        
        case 98: return .noah
        
        case 99: return .shem
        
        case 100: return .arphaxad
        
        case 101: return .cainan
        
        case 102: return .shelah
        
        case 103: return .eber
        
        case 104: return .peleg
        
        case 105: return .reu
        
        case 106: return .serug
        
        case 107: return .nahor
        
        case 108: return .terrah
        
        case 109: return .abraham
        
        case 110: return .isaac
        
        case 111: return .jacob
        
        case 112: return .israel
        
        case 113: return .reuben
        
        case 114: return .amram
        
        case 115: return .jochebed
        
        case 116: return .moses
        
        case 117: return .aaron
        
        case 118: return .perez
        
        case 119: return .hezron
        
        case 120: return .ram
        
        case 121: return .amminadab
        
        case 122: return .nashon
        
        case 123: return .salmon
        
        case 124: return .boaz
        
        case 125: return .obed
        
        case 126: return .jesse
        
        case 127: return .david
        
        case 128: return .nathan
        
        case 129: return .mattatha
        
        case 130: return .menna
        
        case 131: return .melea
        
        case 132: return .eliakim
        
        case 133: return .jonam
        
        case 134: return .judah
        
        case 135: return .simeon
        
        case 136: return .jorim
        
        case 137: return .eliezer
        
        case 138: return .er
        
        case 139: return .elmadam
        
        case 140: return .cosam
        
        case 141: return .addi
        
        case 142: return .neri
        
        case 143: return .shealtiel
        
        case 144: return .zerubbabel
        
        case 145: return .rhesa
        
        case 146: return .joanan
        
        case 147: return .joda
        
        case 148: return .josek
        
        case 149: return .semein
        
        case 150: return .maath
        
        case 151: return .naggai
        
        case 152: return .esli
        
        case 153: return .mattathias
        
        case 154: return .jannai
        
        case 155: return .melki
        
        case 156: return .levi
        
        case 157: return .matthat
        
        case 158: return .heli
        
        case 159: return .joseph
        
        case 160: return .mercury
        
        case 161: return .diana
        
        case 162: return .romulus
        
        case 163: return .remus
        
        case 164: return .socrates
        
        case 165: return .plato
        
        case 166: return .aristotle
        
        case 167: return .alexander
        
        case 168: return .caesar
        
        case 169: return .cicero
        
        case 170: return .jesus
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Name, into buf: inout [UInt8]) {
        switch value {
        
        
        case .god:
            writeInt(&buf, Int32(1))
        
        
        case .cronos:
            writeInt(&buf, Int32(2))
        
        
        case .cronus:
            writeInt(&buf, Int32(3))
        
        
        case .kronos:
            writeInt(&buf, Int32(4))
        
        
        case .zeus:
            writeInt(&buf, Int32(5))
        
        
        case .hera:
            writeInt(&buf, Int32(6))
        
        
        case .leto:
            writeInt(&buf, Int32(7))
        
        
        case .hermes:
            writeInt(&buf, Int32(8))
        
        
        case .apollo:
            writeInt(&buf, Int32(9))
        
        
        case .artemis:
            writeInt(&buf, Int32(10))
        
        
        case .achilles:
            writeInt(&buf, Int32(11))
        
        
        case .philip:
            writeInt(&buf, Int32(12))
        
        
        case .cyrus:
            writeInt(&buf, Int32(13))
        
        
        case .יֵשׁוּ:
            writeInt(&buf, Int32(14))
        
        
        case .יֵשׁוּעַ:
            writeInt(&buf, Int32(15))
        
        
        case .ἰησοῦς:
            writeInt(&buf, Int32(16))
        
        
        case .iesus:
            writeInt(&buf, Int32(17))
        
        
        case .genesis:
            writeInt(&buf, Int32(18))
        
        
        case .exodus:
            writeInt(&buf, Int32(19))
        
        
        case .leviticus:
            writeInt(&buf, Int32(20))
        
        
        case .numbers:
            writeInt(&buf, Int32(21))
        
        
        case .deuteronomy:
            writeInt(&buf, Int32(22))
        
        
        case .joshua:
            writeInt(&buf, Int32(23))
        
        
        case .judges:
            writeInt(&buf, Int32(24))
        
        
        case .ruth:
            writeInt(&buf, Int32(25))
        
        
        case .samuelI:
            writeInt(&buf, Int32(26))
        
        
        case .samuelIi:
            writeInt(&buf, Int32(27))
        
        
        case .kingsI:
            writeInt(&buf, Int32(28))
        
        
        case .kingsIi:
            writeInt(&buf, Int32(29))
        
        
        case .chroniclesI:
            writeInt(&buf, Int32(30))
        
        
        case .chroniclesIi:
            writeInt(&buf, Int32(31))
        
        
        case .ezra:
            writeInt(&buf, Int32(32))
        
        
        case .nehemiah:
            writeInt(&buf, Int32(33))
        
        
        case .esther:
            writeInt(&buf, Int32(34))
        
        
        case .job:
            writeInt(&buf, Int32(35))
        
        
        case .psalms:
            writeInt(&buf, Int32(36))
        
        
        case .proverbs:
            writeInt(&buf, Int32(37))
        
        
        case .ecclesiastes:
            writeInt(&buf, Int32(38))
        
        
        case .songOfSolomon:
            writeInt(&buf, Int32(39))
        
        
        case .isaiah:
            writeInt(&buf, Int32(40))
        
        
        case .jeremiah:
            writeInt(&buf, Int32(41))
        
        
        case .lamentations:
            writeInt(&buf, Int32(42))
        
        
        case .ezekiel:
            writeInt(&buf, Int32(43))
        
        
        case .daniel:
            writeInt(&buf, Int32(44))
        
        
        case .hosea:
            writeInt(&buf, Int32(45))
        
        
        case .joel:
            writeInt(&buf, Int32(46))
        
        
        case .amos:
            writeInt(&buf, Int32(47))
        
        
        case .obadiah:
            writeInt(&buf, Int32(48))
        
        
        case .jonah:
            writeInt(&buf, Int32(49))
        
        
        case .micah:
            writeInt(&buf, Int32(50))
        
        
        case .nahum:
            writeInt(&buf, Int32(51))
        
        
        case .habakkuk:
            writeInt(&buf, Int32(52))
        
        
        case .zephaniah:
            writeInt(&buf, Int32(53))
        
        
        case .haggai:
            writeInt(&buf, Int32(54))
        
        
        case .zechariah:
            writeInt(&buf, Int32(55))
        
        
        case .malachi:
            writeInt(&buf, Int32(56))
        
        
        case .matthew:
            writeInt(&buf, Int32(57))
        
        
        case .mark:
            writeInt(&buf, Int32(58))
        
        
        case .luke:
            writeInt(&buf, Int32(59))
        
        
        case .john:
            writeInt(&buf, Int32(60))
        
        
        case .acts:
            writeInt(&buf, Int32(61))
        
        
        case .romans:
            writeInt(&buf, Int32(62))
        
        
        case .corinthiansI:
            writeInt(&buf, Int32(63))
        
        
        case .corinthiansIi:
            writeInt(&buf, Int32(64))
        
        
        case .galatians:
            writeInt(&buf, Int32(65))
        
        
        case .ephesians:
            writeInt(&buf, Int32(66))
        
        
        case .philippians:
            writeInt(&buf, Int32(67))
        
        
        case .colossians:
            writeInt(&buf, Int32(68))
        
        
        case .thessaloniansI:
            writeInt(&buf, Int32(69))
        
        
        case .thessaloniansIi:
            writeInt(&buf, Int32(70))
        
        
        case .timothyI:
            writeInt(&buf, Int32(71))
        
        
        case .timothyIi:
            writeInt(&buf, Int32(72))
        
        
        case .titus:
            writeInt(&buf, Int32(73))
        
        
        case .philemon:
            writeInt(&buf, Int32(74))
        
        
        case .hebrews:
            writeInt(&buf, Int32(75))
        
        
        case .james:
            writeInt(&buf, Int32(76))
        
        
        case .peterI:
            writeInt(&buf, Int32(77))
        
        
        case .peterIi:
            writeInt(&buf, Int32(78))
        
        
        case .johnI:
            writeInt(&buf, Int32(79))
        
        
        case .johnIi:
            writeInt(&buf, Int32(80))
        
        
        case .johnIii:
            writeInt(&buf, Int32(81))
        
        
        case .jude:
            writeInt(&buf, Int32(82))
        
        
        case .revelation:
            writeInt(&buf, Int32(83))
        
        
        case .yahweh:
            writeInt(&buf, Int32(84))
        
        
        case .mary:
            writeInt(&buf, Int32(85))
        
        
        case .adam:
            writeInt(&buf, Int32(86))
        
        
        case .eve:
            writeInt(&buf, Int32(87))
        
        
        case .cain:
            writeInt(&buf, Int32(88))
        
        
        case .abel:
            writeInt(&buf, Int32(89))
        
        
        case .seth:
            writeInt(&buf, Int32(90))
        
        
        case .enosh:
            writeInt(&buf, Int32(91))
        
        
        case .kenan:
            writeInt(&buf, Int32(92))
        
        
        case .mahalalel:
            writeInt(&buf, Int32(93))
        
        
        case .jared:
            writeInt(&buf, Int32(94))
        
        
        case .enoch:
            writeInt(&buf, Int32(95))
        
        
        case .methuselah:
            writeInt(&buf, Int32(96))
        
        
        case .lamech:
            writeInt(&buf, Int32(97))
        
        
        case .noah:
            writeInt(&buf, Int32(98))
        
        
        case .shem:
            writeInt(&buf, Int32(99))
        
        
        case .arphaxad:
            writeInt(&buf, Int32(100))
        
        
        case .cainan:
            writeInt(&buf, Int32(101))
        
        
        case .shelah:
            writeInt(&buf, Int32(102))
        
        
        case .eber:
            writeInt(&buf, Int32(103))
        
        
        case .peleg:
            writeInt(&buf, Int32(104))
        
        
        case .reu:
            writeInt(&buf, Int32(105))
        
        
        case .serug:
            writeInt(&buf, Int32(106))
        
        
        case .nahor:
            writeInt(&buf, Int32(107))
        
        
        case .terrah:
            writeInt(&buf, Int32(108))
        
        
        case .abraham:
            writeInt(&buf, Int32(109))
        
        
        case .isaac:
            writeInt(&buf, Int32(110))
        
        
        case .jacob:
            writeInt(&buf, Int32(111))
        
        
        case .israel:
            writeInt(&buf, Int32(112))
        
        
        case .reuben:
            writeInt(&buf, Int32(113))
        
        
        case .amram:
            writeInt(&buf, Int32(114))
        
        
        case .jochebed:
            writeInt(&buf, Int32(115))
        
        
        case .moses:
            writeInt(&buf, Int32(116))
        
        
        case .aaron:
            writeInt(&buf, Int32(117))
        
        
        case .perez:
            writeInt(&buf, Int32(118))
        
        
        case .hezron:
            writeInt(&buf, Int32(119))
        
        
        case .ram:
            writeInt(&buf, Int32(120))
        
        
        case .amminadab:
            writeInt(&buf, Int32(121))
        
        
        case .nashon:
            writeInt(&buf, Int32(122))
        
        
        case .salmon:
            writeInt(&buf, Int32(123))
        
        
        case .boaz:
            writeInt(&buf, Int32(124))
        
        
        case .obed:
            writeInt(&buf, Int32(125))
        
        
        case .jesse:
            writeInt(&buf, Int32(126))
        
        
        case .david:
            writeInt(&buf, Int32(127))
        
        
        case .nathan:
            writeInt(&buf, Int32(128))
        
        
        case .mattatha:
            writeInt(&buf, Int32(129))
        
        
        case .menna:
            writeInt(&buf, Int32(130))
        
        
        case .melea:
            writeInt(&buf, Int32(131))
        
        
        case .eliakim:
            writeInt(&buf, Int32(132))
        
        
        case .jonam:
            writeInt(&buf, Int32(133))
        
        
        case .judah:
            writeInt(&buf, Int32(134))
        
        
        case .simeon:
            writeInt(&buf, Int32(135))
        
        
        case .jorim:
            writeInt(&buf, Int32(136))
        
        
        case .eliezer:
            writeInt(&buf, Int32(137))
        
        
        case .er:
            writeInt(&buf, Int32(138))
        
        
        case .elmadam:
            writeInt(&buf, Int32(139))
        
        
        case .cosam:
            writeInt(&buf, Int32(140))
        
        
        case .addi:
            writeInt(&buf, Int32(141))
        
        
        case .neri:
            writeInt(&buf, Int32(142))
        
        
        case .shealtiel:
            writeInt(&buf, Int32(143))
        
        
        case .zerubbabel:
            writeInt(&buf, Int32(144))
        
        
        case .rhesa:
            writeInt(&buf, Int32(145))
        
        
        case .joanan:
            writeInt(&buf, Int32(146))
        
        
        case .joda:
            writeInt(&buf, Int32(147))
        
        
        case .josek:
            writeInt(&buf, Int32(148))
        
        
        case .semein:
            writeInt(&buf, Int32(149))
        
        
        case .maath:
            writeInt(&buf, Int32(150))
        
        
        case .naggai:
            writeInt(&buf, Int32(151))
        
        
        case .esli:
            writeInt(&buf, Int32(152))
        
        
        case .mattathias:
            writeInt(&buf, Int32(153))
        
        
        case .jannai:
            writeInt(&buf, Int32(154))
        
        
        case .melki:
            writeInt(&buf, Int32(155))
        
        
        case .levi:
            writeInt(&buf, Int32(156))
        
        
        case .matthat:
            writeInt(&buf, Int32(157))
        
        
        case .heli:
            writeInt(&buf, Int32(158))
        
        
        case .joseph:
            writeInt(&buf, Int32(159))
        
        
        case .mercury:
            writeInt(&buf, Int32(160))
        
        
        case .diana:
            writeInt(&buf, Int32(161))
        
        
        case .romulus:
            writeInt(&buf, Int32(162))
        
        
        case .remus:
            writeInt(&buf, Int32(163))
        
        
        case .socrates:
            writeInt(&buf, Int32(164))
        
        
        case .plato:
            writeInt(&buf, Int32(165))
        
        
        case .aristotle:
            writeInt(&buf, Int32(166))
        
        
        case .alexander:
            writeInt(&buf, Int32(167))
        
        
        case .caesar:
            writeInt(&buf, Int32(168))
        
        
        case .cicero:
            writeInt(&buf, Int32(169))
        
        
        case .jesus:
            writeInt(&buf, Int32(170))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeName_lift(_ buf: RustBuffer) throws -> Name {
    return try FfiConverterTypeName.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeName_lower(_ value: Name) -> RustBuffer {
    return FfiConverterTypeName.lower(value)
}


private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_name_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureNameInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all