uniffi::setup_scaffolding!();

use serde::Serialize;
use std::fmt;

#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash, Serialize, uniffi::Enum)]
pub enum Name {
    //
    God,

    // greece
    Cronos,
    Cronus,
    Kronos,
    Zeus,
    Hera,
    Leto,
    Hermes,
    Apollo,
    Artemis,
    Achilles,
    Philip,

    // persia
    Cyrus,

    // israel
    יֵשׁוּ,
    יֵשׁוּעַ,

    // // books
    // // // old
    Genesis,
    Exodus,
    Leviticus,
    Numbers,
    Deuteronomy,
    Joshua,
    Judges,
    Ruth,
    SamuelI,
    SamuelII,
    KingsI,
    KingsII,
    ChroniclesI,
    ChroniclesII,
    Ezra,
    Nehemiah,
    Esther,
    Job,
    Psalms,
    Proverbs,
    Ecclesiastes,
    SongOfSolomon,
    Isaiah,
    Jeremiah,
    Lamentations,
    Ezekiel,
    Daniel,
    Hosea,
    Joel,
    Amos,
    Obadiah,
    Jonah,
    Micah,
    Nahum,
    Habakkuk,
    Zephaniah,
    Haggai,
    Zechariah,
    Malachi,

    // // // new
    Matthew,
    Mark,
    Luke,
    John,
    Acts,
    Romans,
    CorinthiansI,
    CorinthiansII,
    Galatians,
    Ephesians,
    Philippians,
    Colossians,
    ThessaloniansI,
    ThessaloniansII,
    TimothyI,
    TimothyII,
    Titus,
    Philemon,
    Hebrews,
    James,
    PeterI,
    PeterII,
    JohnI,
    JohnII,
    JohnIII,
    Jude,
    Revelation,

    // // characters
    Yahweh,
    Mary,
    Adam,
    Eve,
    Cain,
    Abel,
    Seth,
    Enosh,
    Kenan,
    Mahalalel,
    Jared,
    Enoch,
    Methuselah,
    Lamech,
    Noah,
    Shem,
    Arphaxad,
    Cainan,
    Shelah,
    Eber,
    Peleg,
    Reu,
    Serug,
    Nahor,
    Terrah,
    Abraham,
    Isaac,
    Jacob,
    Israel,
    Reuben,
    Amram,
    Jochebed,
    Moses,
    Aaron,
    Perez,
    Hezron,
    Ram,
    Amminadab,
    Nashon,
    Salmon,
    Boaz,
    Obed,
    Jesse,
    David,
    Nathan,
    Mattatha,
    Menna,
    Melea,
    Eliakim,
    Jonam,
    Judah,
    Simeon,
    Jorim,
    Eliezer,
    Er,
    Elmadam,
    Cosam,
    Addi,
    Neri,
    Shealtiel,
    Zerubbabel,
    Rhesa,
    Joanan,
    Joda,
    Josek,
    Semein,
    Maath,
    Naggai,
    Esli,
    Mattathias,
    Jannai,
    Melki,
    Levi,
    Matthat,
    Heli,
    Joseph,

    // rome
    Mercury,
    Diana,
    Romulus,
    Remus,
    Socrates,
    Plato,
    Aristotle,
    Alexander,
    Caesar,
    Cicero,
    Jesus,
}

impl fmt::Display for Name {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{:?}", self)
    }
}

pub const BIBLE: [Name; 66] = [
    Name::Genesis,
    Name::Exodus,
    Name::Leviticus,
    Name::Numbers,
    Name::Deuteronomy,
    Name::Joshua,
    Name::Judges,
    Name::Ruth,
    Name::SamuelI,
    Name::SamuelII,
    Name::KingsI,
    Name::KingsII,
    Name::ChroniclesI,
    Name::ChroniclesII,
    Name::Ezra,
    Name::Nehemiah,
    Name::Esther,
    Name::Job,
    Name::Psalms,
    Name::Proverbs,
    Name::Ecclesiastes,
    Name::SongOfSolomon,
    Name::Isaiah,
    Name::Jeremiah,
    Name::Lamentations,
    Name::Ezekiel,
    Name::Daniel,
    Name::Hosea,
    Name::Joel,
    Name::Amos,
    Name::Obadiah,
    Name::Jonah,
    Name::Micah,
    Name::Nahum,
    Name::Habakkuk,
    Name::Zephaniah,
    Name::Haggai,
    Name::Zechariah,
    Name::Malachi,
    Name::Matthew,
    Name::Mark,
    Name::Luke,
    Name::John,
    Name::Acts,
    Name::Romans,
    Name::CorinthiansI,
    Name::CorinthiansII,
    Name::Galatians,
    Name::Ephesians,
    Name::Philippians,
    Name::Colossians,
    Name::ThessaloniansI,
    Name::ThessaloniansII,
    Name::TimothyI,
    Name::TimothyII,
    Name::Titus,
    Name::Philemon,
    Name::Hebrews,
    Name::James,
    Name::PeterI,
    Name::PeterII,
    Name::JohnI,
    Name::JohnII,
    Name::JohnIII,
    Name::Jude,
    Name::Revelation,
];
